# Figure 5 | Sample-to-reference ratio analysis

# 0. Setup ----
source("scripts/_project_setup.R")
use_packages(c("data.table", "tidyverse", "readxl", "ggridges", "ggpattern", "ggpubr", "patchwork", "ggtext", "ggpp", "openxlsx", "showtext", "grid", "brms", "irr"))
source("utils/figure_style.R")
source("utils/imputation.R")
source("utils/benchmark_metrics.R")
plasmix_theme <- if (is.function(theme_plasmix)) theme_plasmix() else theme_plasmix
showtext_auto(); showtext_opts(dpi = 600)
label_style <- list(size = 12, face = "bold")

# 1. Inputs ----
paths <- c(metadata = "data/study_metadata.xlsx", feature_metadata = "data/feature_metadata.tsv.gz", detection = "results/detection_status.tsv.gz",
           profiles = "data/protein_profiles_long.tsv.gz", dea = "results/dea_df_multi.tsv.gz", dea_consensus = "results/ed5_dea_consensus.tsv.gz")
missing_inputs <- paths[!file.exists(paths)]
if (length(missing_inputs)) stop("Missing Figure 5 inputs: \n", paste(missing_inputs, collapse = "\n"),
                                "\ned5_dea_consensus.tsv.gz is generated by ed5_mfnp_contrast_difference.R.")

meta_batch <- read_xlsx(paths["metadata"], sheet = "batch")
study_samples <- c("M", "Y", "P", "X", "F", "N")
meta_sample <- read_xlsx(paths["metadata"], sheet = "sample") %>% filter(Sample %in% study_samples)
meta_batch_physics <- read_xlsx(paths["metadata"], sheet = "variance")
feat_meta <- fread(paths["feature_metadata"]) %>% filter(!Is_Protein_Group, !Is_Unknown)
valid_features <- unique(feat_meta$UniqueID)
lod_status <- fread(paths["detection"])
long_df <- fread(paths["profiles"])
dea_df_multi <- fread(paths["dea"])

# 2. PVCA (Before SRR) ----
meta_batch_ht <- meta_batch %>% filter(Platform %in% c("SOM", "OLK", "DIA"), !Batch %in% c('OLK_P1_B1', 'OLK_P1_B2'))
meta_sample_ht <- meta_sample %>% filter(Batch %in% meta_batch_ht$Batch)

long_df_filter <- long_df %>%
    filter(UniqueID %in% valid_features, Sample %in% study_samples,
          (Platform %in% c("DIA", "AAG") & DataTier == "Baseline") | (Platform %in% c("OLK", "SOM", "NLS") & DataTier == "Calibrated"))

keep_features <- lod_status %>%
    filter(Batch %in% meta_batch_ht$Batch, IsDetected == TRUE) %>%
    group_by(UniqueID) %>%
    add_count() %>%
    filter(n > length(meta_batch_ht$Batch) * 0.5) %>%
    pull(UniqueID) %>% unique()

pca_expr_filt <- long_df_filter %>%
    filter(ColName %in% meta_sample_ht$ColName, UniqueID %in% keep_features) %>%
    select(UniqueID, ColName, Value) %>%
    pivot_wider(names_from = ColName, values_from = Value) %>%
    column_to_rownames("UniqueID") %>%
    as.matrix()

pca_imputed <- impute_hybrid_global(pca_expr_filt, meta_sample_ht)
pca_res <- prcomp(t(pca_imputed), scale. = TRUE)
pca_var <- (pca_res$sdev^2) / sum(pca_res$sdev^2)
top_n_pc <- max(3, min(which(cumsum(pca_var) >= 0.80)[1], 20))

pvca_data <- as.data.frame(pca_res$x[, 1:top_n_pc]) %>%
    rownames_to_column("ColName") %>%
    left_join(meta_sample %>% select(ColName, Batch, Sample), by = "ColName") %>%
    left_join(meta_batch_physics %>% select(Batch, Surrogate, Preparation, Instrument, Representation), by = "Batch")

calc_variance_bayesian <- function(pc_col, data) {
    formula_str <- paste(pc_col, "~ (1|Surrogate) + (1|Representation) + (1|Preparation) + (1|Instrument) + (1|Sample) +",
                        "(1|Surrogate:Representation) + (1|Surrogate:Preparation) + (1|Surrogate:Instrument) +",
                        "(1|Representation:Preparation) + (1|Representation:Instrument) + (1|Preparation:Instrument)")
    my_priors <- c(set_prior("student_t(3, 0, 10)", class = "sd"), set_prior("normal(0, 10)", class = "Intercept"))
    tryCatch({
        mod <- brm(
            formula = as.formula(formula_str), data = data, family = gaussian(), prior = my_priors,
            chains = 4, iter = 10000, warmup = 2000, cores = 4, refresh = 0, seed = 20260201, control = list(adapt_delta = 0.99)
        )
        res <- sapply(VarCorr(mod), function(x) x$sd[1, "Estimate"]^2)
        c(res, Residual = summary(mod)$spec_pars["sigma", "Estimate"]^2)
    }, error = function(e) { message(paste("Error:", e$message)); NULL })
}
var_components_bayes <- sapply(colnames(pvca_data)[2:(top_n_pc+1)], function(pc) calc_variance_bayesian(pc, pvca_data))
final_components_mat <- if(is.list(var_components_bayes)) do.call(cbind, var_components_bayes[!sapply(var_components_bayes, is.null)]) else var_components_bayes

pc_indices <- as.numeric(gsub("PC", "", colnames(final_components_mat)))
weight_factor <- (pca_res$sdev^2)[pc_indices] / sum((pca_res$sdev^2)[pc_indices])
weighted_var <- rowSums(sweep(final_components_mat, 2, weight_factor, "*"))
weighted_var <- weighted_var[names(weighted_var) != "residual__"]

pvca_plot_data <- data.frame(Effect = names(weighted_var), Proportion = weighted_var / sum(weighted_var)) %>%
    mutate(Effect_Display = factor(gsub(":", " × ", Effect), levels = gsub(":", " × ", Effect)[order(-Proportion)]))

color_map <- c("Representation"="#1F78B4", "Surrogate"="#A6CEE3", "Preparation"="#33A02C", "Instrument"="#B2DF8A", "Residual"="#FB9A99", "Sample"="#E31A1C")
pvca_plot_df <- pvca_plot_data %>%
    rowwise() %>%
    mutate(
        words = list(str_split(as.character(Effect_Display), " × |:")[[1]]),
        p1 = words[1],
        p2 = if(length(words) > 1) words[2] else NA,
        fill_col = if(p1 %in% names(color_map)) color_map[p1] else "#D3D3D3",
        pattern_col = if(!is.na(p2) && p2 %in% names(color_map)) color_map[p2] else fill_col,
        has_pattern = if(!is.na(p2)) "stripe" else "none"
    ) %>% ungroup() %>%
    mutate(
        is_max = Proportion == max(Proportion),
        text_hjust = ifelse(is_max, 1.15, -0.15),
        text_color = ifelse(is_max, "white", "black")
    ) %>% as.data.frame()
p_pvca_final <- ggplot(pvca_plot_df, aes(x = fct_reorder(Effect_Display, Proportion), y = Proportion)) +
    geom_bar_pattern(aes(fill = fill_col, pattern_fill = pattern_col, pattern = has_pattern),
                    stat = "identity", width = 0.68, color = NA, pattern_color = NA,
                    pattern_density = 0.5, pattern_spacing = 0.02, pattern_angle = 45) +
    geom_text(aes(label = sprintf("%.1f%%", Proportion * 100), hjust = text_hjust, color = text_color), size = 2.8, fontface = "bold") +
    scale_fill_identity() + scale_pattern_fill_identity() + scale_pattern_identity() + scale_color_identity() +
    scale_y_continuous(expand = c(0,0), limits = c(0, max(pvca_plot_df$Proportion) * 1.0)) +
    labs(x = NULL, y = "Proportion of variance") +
    plasmix_theme + coord_flip() +
    theme(
        panel.grid.major = element_blank(),
        axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        axis.line.x = element_blank(), axis.line.y = element_line(color = "black", linewidth = 0.5)
    )

# 3. Ridge before/after SRR based on baseline data ----
df_baseline <- long_df %>% filter(UniqueID %in% valid_features, Sample %in% study_samples, DataTier == "Baseline", Batch %in% meta_batch_ht$Batch)
ref_anchors <- df_baseline %>% group_by(Batch, UniqueID) %>% summarize(Ref_Val = mean(Value[Sample == "P"], na.rm = TRUE))
df_srr <- df_baseline %>% left_join(ref_anchors) %>% mutate(SRR_Value = Value - Ref_Val)
plot_srr_ridge <- df_srr %>%
    pivot_longer(cols = c(Value, SRR_Value), names_to = "Method", values_to = "Val") %>%
    mutate(Method = factor(Method, levels = c("Value", "SRR_Value"), c("Before SRR", "After SRR")))

batch_order <- meta_batch %>%
    filter(Batch %in% unique(plot_srr_ridge$Batch)) %>%
    arrange(Batch) %>% pull(Batch)
plot_srr_ridge$Batch <- factor(plot_srr_ridge$Batch, levels = rev(batch_order))

draw_sub_plot <- function(data_subset, x_label, x_limits) {
    ggplot(data_subset, aes(x = Val, y = Batch, fill = Platform, color = Platform)) +
        geom_density_ridges(alpha = 0.5, scale = 1.3, rel_min_height = 0.005, linewidth = 0.3, quantile_lines = TRUE) +
        scale_fill_manual(values = platform_color) +
        scale_color_manual(values = platform_color) +
        labs(y = NULL) +
        facet_grid(~Method, scales = "free_x") +
        scale_x_continuous(name = x_label, limits = x_limits, expand = c(0,0)) +
        scale_y_discrete(expand = expansion(mult = c(0.01, 0.1))) +
        plasmix_theme +
        theme(panel.border = element_rect(color = "black", fill = NA, linewidth = 0.35), axis.line.x = element_blank(), axis.line.y = element_blank()) +
        theme(panel.grid.major.y = element_blank(), legend.position = "none", axis.text.y = element_text(size = 7))
}
p1 <- draw_sub_plot(filter(plot_srr_ridge, Method == "Before SRR"), expression(log[2] * "Intensity"), c(-4, 34)) + theme(plot.margin = margin(0, 0, 0, 0, "pt"))
p2 <- draw_sub_plot(filter(plot_srr_ridge, Method == "After SRR"), expression(log[2] * "Ratio"), c(-2.3, 2.3)) + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + theme(plot.margin = margin(0, 0, 0, 0, "pt"))
p_srr_ridge <- p1 + p2 + plot_layout(ncol = 2)

# 4. PCA (Before & After SRR) ----
meta_batch_hq <- meta_batch %>% filter(Batch %in% c("SOM_P1_B2", "SOM_P2_B1", "DIA_P1_B1", "DIA_P2_B1", "OLK_P2_B1", "OLK_P2_B2"))
meta_sample_hq <- meta_sample %>% filter(Batch %in% meta_batch_hq$Batch, Sample %in% c("M", "Y", "P", "X", "F")) %>% filter(ColName != "OLK_P2_B1_X_FDU_1")

keep_features <- lod_status %>%
    filter(Batch %in% meta_batch_hq$Batch, IsDetected == TRUE, P == TRUE) %>%
    group_by(UniqueID) %>%
    add_count() %>%
    filter(n > length(meta_batch_hq$Batch) * 0.8) %>%
    pull(UniqueID) %>% unique()

pca_expr_filt <- df_baseline %>%
    filter(UniqueID %in% keep_features, ColName %in% meta_sample_hq$ColName) %>%
    select(UniqueID, ColName, Value) %>%
    pivot_wider(names_from = ColName, values_from = Value) %>%
    column_to_rownames("UniqueID") %>%
    as.matrix()

pca_expr_filt <- pca_expr_filt[, meta_sample_hq$ColName]
pca_imputed <- impute_knn(pca_expr_filt, meta_sample_hq)

ref_anchors <- df_baseline %>% group_by(Batch, UniqueID) %>% summarize(Ref_Val = mean(Value[Sample == "P"], na.rm = TRUE))
df_srr <- df_baseline %>% left_join(ref_anchors) %>% mutate(SRR_Value = Value - Ref_Val)
expr_srr <- df_srr %>% filter(ColName %in% unique(meta_sample_hq$ColName)) %>% select(UniqueID, ColName, SRR_Value) %>% pivot_wider(names_from = ColName, values_from = SRR_Value) %>% column_to_rownames("UniqueID")
pca_imputed_srr <- impute_knn(expr_srr[keep_features, ], meta_sample_hq)

plot_pca_advanced <- function(exprMat, metaMat, title_text = NULL, par_scale = FALSE, show_batch = FALSE) {
    sel_cols <- intersect(colnames(exprMat), metaMat$ColName)
    exprMat <- as.data.frame(exprMat) %>% select(all_of(sel_cols))
    metaMat <- metaMat %>% filter(ColName %in% sel_cols)
    exprMat <- exprMat[which(apply(exprMat, 1, var, na.rm = TRUE) != 0), ]
    group <- metaMat$Sample[match(colnames(exprMat), metaMat$ColName)]
    snrvalue <- round(calc_pca_snr(exprMat, group, center = TRUE, scale. = par_scale), 2)
    pca_prcomp <- prcomp(t(exprMat), retx = TRUE, center = TRUE, scale. = par_scale)
    pcs <- as.data.frame(predict(pca_prcomp))
    max_x <- max(abs(pcs$PC1), na.rm = TRUE)
    max_y <- max(abs(pcs$PC2), na.rm = TRUE)
    pcs$Group <- factor(group, levels = c('M', 'Y', 'P', 'X', 'F', 'N'))
    if (show_batch) { pcs$Batch <- factor(metaMat$Batch[match(colnames(exprMat), metaMat$ColName)])}
    aes_map <- aes(x = PC1, y = PC2, color = Group, fill = Group, group = Group)
    if (show_batch) aes_map$shape <- quo(Batch)
    p <- ggplot(pcs, mapping = aes_map) +
        # stat_chull(geom = "polygon", alpha = 0.15, linetype = "dotted", linewidth = 0.5, show.legend = FALSE) +
        geom_point(size = 1) +
        scale_color_manual(values = sample_color) +
        scale_fill_manual(values = sample_color) +
        labs(x = sprintf("PC1 (%.0f%%)", summary(pca_prcomp)$importance[2, 1] * 100),
            y = sprintf("PC2 (%.0f%%)", summary(pca_prcomp)$importance[2, 2] * 100),
            title = title_text, subtitle = paste0("*SNR* = ", snrvalue, ", *n* = ", prettyNum(nrow(exprMat), big.mark = ","))) +
        plasmix_theme +
        theme(
            axis.title = element_text(size = 7.5, color = "black"), axis.text = element_text(size = 7, color = "black"),
            axis.title.x = element_text(margin = margin(t = 1)), axis.title.y = element_text(margin = margin(r = 1)),
            plot.title = element_text(face = "bold", size = 7.5, hjust = 0.5, margin = margin(t = 1, b = 1.1)),
            plot.subtitle = element_markdown(face = "plain", size = 7.5, hjust = 0.5, margin = margin(b = 1.1)),
            legend.position = "right",
            legend.margin = margin(0, 5, 5, 5),
            panel.grid.major = element_blank(),
            panel.border = element_rect(color = "black", fill = NA, linewidth = 0.35),
            axis.line.x = element_blank(), axis.line.y = element_blank()
        )
    list(p = p, max_x = max_x, max_y = max_y, scores = pcs)
}

p_pca_before <- plot_pca_advanced(pca_imputed, meta_sample_hq %>% filter(Sample != 'P'), title_text = "Before SRR", par_scale = TRUE, show_batch = TRUE)
p_pca_after  <- plot_pca_advanced(pca_imputed_srr, meta_sample_hq %>% filter(Sample != 'P'), title_text = "After SRR", par_scale = TRUE, show_batch = TRUE)
lim_x <- max(p_pca_before$max_x, p_pca_after$max_x)
lim_y <- max(p_pca_before$max_y, p_pca_after$max_y)
p1_locked <- p_pca_before$p +
    coord_cartesian(xlim = c(-lim_x, lim_x), ylim = c(-lim_y, lim_y)) +
    theme(legend.box = "vertical", legend.key.size = unit(0.3, "lines"), legend.spacing.y = unit(0, "cm")) +
    guides(color = guide_legend(nrow = 1, byrow = TRUE, title = "Group", order = 1),
          fill  = guide_legend(nrow = 1, byrow = TRUE, title = "Group", order = 1),
          shape = guide_legend(nrow = 2, byrow = FALSE, title = "Batch", order = 2))
p2_locked <- p_pca_after$p + coord_cartesian(xlim = c(-lim_x, lim_x), ylim = c(-lim_y, lim_y))
fig_pca_combo <- ggarrange(p1_locked, p2_locked, ncol = 2, align = "h", common.legend = TRUE, legend = "bottom")
pca_scores_source <- bind_rows(p_pca_before$scores %>% mutate(Method = "Before SRR"), p_pca_after$scores %>% mutate(Method = "After SRR"))

# 5. Density plot of ICC ----
dea_merge <- fread(paths["dea_consensus"])
global_sig_mf <- dea_merge %>% filter(Pair == "M/F") %>% mutate(Class = ifelse(Label %in% c("Up", "Down"), "DEP (M/F)", "Non-DEP"))

calculate_icc_from_long <- function(df_long, label_name) {
    df_clean <- df_long %>%
        filter(Sample %in% c("M", "F", "X", "Y")) %>%
        group_by(UniqueID, Batch, Sample) %>%
        summarize(Value = mean(Value, na.rm = TRUE), .groups = "drop")
    prots <- unique(df_clean$UniqueID)
    results <- map_dfr(prots, function(p) {
        mat_p <- df_clean %>%
            filter(UniqueID == p) %>%
            pivot_wider(id_cols = Sample, names_from = Batch, values_from = Value) %>%
            column_to_rownames("Sample") %>% as.matrix()
        valid_cols <- colSums(!is.na(mat_p)) >= 3
        icc_val <- NA_real_
        if (sum(valid_cols) >= 2) {
            mat_p <- mat_p[, valid_cols, drop = FALSE]
            if (var(as.vector(mat_p), na.rm = TRUE) > 0) {
                icc_val <- tryCatch({
                    res <- icc(mat_p, model = "twoway", type = "agreement", unit = "single")
                    as.numeric(res$value)
                }, error = function(e) NA_real_)
            }
        }
        tibble(UniqueID = p, ICC = icc_val, Category = label_name)
    })
    return(results)
}

df_icc_before <- df_baseline %>% filter(Batch %in% meta_batch_hq$Batch) %>% select(UniqueID, Batch, Sample, Value)
icc_res_before <- calculate_icc_from_long(df_icc_before, "Before SRR")

df_icc_after <- df_srr %>% filter(Batch %in% meta_batch_hq$Batch) %>% select(UniqueID, Batch, Sample, Value = SRR_Value)
icc_res_after <- calculate_icc_from_long(df_icc_after, "After SRR")

icc_plot_df <- bind_rows(icc_res_before, icc_res_after) %>%
    filter(!is.na(ICC)) %>%
    mutate(Category = factor(Category, levels = c("Before SRR", "After SRR"))) %>%
    left_join(global_sig_mf %>% select(UniqueID, Class), by = "UniqueID") %>%
    mutate(Class = replace_na(Class, "Non-DEP"), Class = factor(Class, levels = c("Non-DEP", "DEP (M/F)")))

categorize_icc <- function(icc_val) {
    case_when(
        is.na(icc_val) ~ "NA",
        icc_val < 0.50 ~ "Poor (<0.50)",
        icc_val >= 0.50 & icc_val < 0.75 ~ "Moderate (0.50-0.75)",
        icc_val >= 0.75 & icc_val < 0.90 ~ "Good (0.75-0.90)",
        icc_val >= 0.90 ~ "Excellent (>=0.90)"
    )
}

icc_summary <- icc_plot_df %>%
    mutate(ICC_Clean = ifelse(ICC < 0, 0, ICC), ICC_Tier = categorize_icc(ICC_Clean),
          ICC_Tier = factor(ICC_Tier, levels = c("Poor (<0.50)", "Moderate (0.50-0.75)", "Good (0.75-0.90)", "Excellent (>=0.90)"))) %>%
    group_by(Category, Class, ICC_Tier) %>%
    summarise(Count = n(), .groups = "drop_last") %>%
    mutate(Percentage = sprintf("%.1f%%", Count / sum(Count) * 100)) %>%
    ungroup() %>%
    pivot_wider(id_cols = c(Category, Class), names_from = ICC_Tier, values_from = c(Count, Percentage),
                names_glue = "{ICC_Tier}_{.value}")

print(as.data.frame(icc_summary))

icc_threshold_summary <- icc_plot_df %>%
    filter(Class == "DEP (M/F)") %>%
    group_by(Category) %>%
    summarise(ICC_ge_050 = mean(ICC > .50) * 100, ICC_ge_075 = mean(ICC > .75) * 100,
              ICC_ge_090 = mean(ICC > .90) * 100, .groups = "drop")

before_stats <- icc_threshold_summary %>% filter(Category == "Before SRR")
after_stats <- icc_threshold_summary %>% filter(Category == "After SRR")

icc_table_df <- tibble(
    Row = rep(c("Header", "Before SRR", "After SRR"), each = 4),
    Column = rep(c("Label", "ICC050", "ICC075", "ICC090"), 3),
    Label = c(
        "ICC threshold", "> 0.50", "> 0.75", "> 0.90",
        "Before SRR", sprintf("%.1f%%", before_stats$ICC_ge_050), sprintf("%.1f%%", before_stats$ICC_ge_075), sprintf("%.1f%%", before_stats$ICC_ge_090),
        "After SRR", sprintf("%.1f%%", after_stats$ICC_ge_050), sprintf("%.1f%%", after_stats$ICC_ge_075), sprintf("%.1f%%", after_stats$ICC_ge_090)
    )) %>%
    mutate(
        xmin = case_when(Column == "Label" ~ 0, Column == "ICC050" ~ .4, Column == "ICC075" ~ .6, TRUE ~ .8),
        xmax = case_when(Column == "Label" ~ .4, Column == "ICC050" ~ .6, Column == "ICC075" ~ .8, TRUE ~ 1),
        ymin = case_when(Row == "After SRR" ~ 1, Row == "Before SRR" ~ 2, TRUE ~ 3),
        ymax = ymin + 1,
        x = if_else(Column == "Label", xmin + .03, (xmin + xmax) / 2),
        y = (ymin + ymax) / 2,
        hjust = if_else(Column == "Label", 0, .5),
        Cell_type = case_when(Row == "Header" ~ "Header", Column == "Label" ~ "Row label", TRUE ~ "Value")
    )

p_icc_table <- ggplot(icc_table_df) +
    geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = Cell_type),
              color = "white", linewidth = .4) +
    geom_text(aes(x = x, y = y, label = Label, color = Cell_type, hjust = hjust), size = 2.5, fontface = "bold") +
    annotate("rect", xmin = 0, xmax = 1, ymin = 1, ymax = 4, fill = NA, color = "#8FBCAF", linewidth = .35) +
    scale_fill_manual(values = c("Header" = "#DCEFEA", "Row label" = "#EEF7F4", "Value" = "#FAFCFB"), guide = "none") +
    scale_color_manual(values = c("Header" = "grey10", "Row label" = "grey10", "Value" = "#00695A"), guide = "none") +
    coord_cartesian(xlim = c(0, 1), ylim = c(0, 3), expand = FALSE, clip = "off") +
    theme_void() +
    theme(plot.background = element_rect(fill = "transparent", color = NA), plot.margin = margin(0, 0, 0, 0))

icc_colors <- c("Non-DEP" = "#d2eae4", "DEP (M/F)" = "#00695a")

p_top <- ggplot(icc_plot_df %>% filter(Category == "After SRR"), aes(x = ICC, y = after_stat(density), fill = Class)) +
    geom_histogram(bins = 200, colour = "black", linewidth = .1, position = "stack") +
    geom_hline(yintercept = 0, color = "black", linewidth = .5) +
    scale_fill_manual("Biological status", values = icc_colors) +
    plasmix_theme +
    scale_y_continuous(expand = expansion(mult = c(0, .05))) +
    scale_x_continuous(breaks = seq(-.5, 1, .25), expand = c(0, 0)) +
    coord_cartesian(xlim = c(-.5, 1)) +
    labs(x = NULL, y = "Density after SRR") +
    theme(
        panel.border = element_blank(),
        axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        legend.position = c(.05, .95),
        legend.justification = c(0, 1),
        legend.key.size = unit(.5, "lines"),
        legend.title = element_text(size = 7, face = "bold", margin = margin(b = 3)),
        legend.text = element_text(size = 7),
        plot.margin = margin(t = 0, r = 5, b = 0, l = 1)
    )

p_bottom <- ggplot(icc_plot_df %>% filter(Category == "Before SRR"), aes(x = ICC, y = after_stat(density), fill = Class)) +
    geom_histogram(bins = 200, colour = "black", linewidth = .1, position = "stack") +
    geom_hline(yintercept = 0, color = "black", linewidth = .5) +
    scale_fill_manual("Consensus DEP", values = icc_colors) +
    plasmix_theme +
    scale_y_reverse(expand = expansion(mult = c(.05, 0))) +
    scale_x_continuous(breaks = seq(-.5, 1, .25), expand = c(0, 0)) +
    coord_cartesian(xlim = c(-.5, 1)) +
    labs(x = "Intraclass correlation coefficient (ICC)", y = "Density before SRR") +
    theme(
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        legend.position = "none",
        plot.margin = margin(t = 0, r = 5, b = 0, l = 1)
    )

p_bottom <- p_bottom + inset_element(
    p_icc_table, left = .43, bottom = .09, right = .995, top = .46,
    align_to = "panel", clip = TRUE
)
p_icc_temple <- p_top + p_bottom + plot_layout(nrow = 2, heights = c(1.5, 1))

# 6. Cross-Platform log2FC Scatter Plots ----
# combo_colors <- c("DIA vs OLK" = "#3C5488", "DIA vs SOM" = "#E64B35", "SOM vs OLK" = "#00A087")
combo_colors <- c("DIA vs OLK" = "#7f404a", "DIA vs SOM" = "#5b4080", "SOM vs OLK" = "#408073")

hq_deps <- dea_df_multi %>% filter(Batch %in% meta_batch_hq$Batch, Pair %in% c("M/F", "N/P"), DataTier == "Baseline", Classification == "Verified-DEP")

platform_consensus <- hq_deps %>%
    group_by(Platform, Pair, UniqueID) %>%
    summarize(n_batches = n_distinct(Batch), .groups = "drop") %>%
    filter(n_batches > 0)

triple_consensus <- platform_consensus %>%
    group_by(Pair, UniqueID) %>%
    summarize(n_plats = n_distinct(Platform), .groups = "drop") %>%
    filter(n_plats == 3) %>%
    mutate(Is_Triple = TRUE)

naive_fc_df <- long_df %>%
    inner_join(lod_status %>% select(Batch, UniqueID, IsDetected), by = c("Batch", "UniqueID")) %>%
    filter(Batch %in% meta_batch_hq$Batch, DataTier == "Baseline", IsDetected == TRUE) %>%
    filter(Sample %in% c("M", "F", "N", "P")) %>%
    group_by(Batch, Platform, UniqueID, Sample) %>%
    summarize(Median_Val = median(Value, na.rm = TRUE), .groups = "drop") %>%
    pivot_wider(names_from = Sample, values_from = Median_Val) %>%
    mutate(`M/F` = M - F, `N/P` = N - P) %>%
    select(Batch, Platform, UniqueID, `M/F`, `N/P`) %>%
    pivot_longer(cols = c(`M/F`, `N/P`), names_to = "Pair", values_to = "logFC_Naive") %>%
    filter(!is.na(logFC_Naive))

build_comp <- function(p1, p2, name) {
    valid_p1 <- platform_consensus %>% filter(Platform == p1) %>% select(Pair, UniqueID)
    valid_p2 <- platform_consensus %>% filter(Platform == p2) %>% select(Pair, UniqueID)
    df_p1 <- naive_fc_df %>% filter(Platform == p1) %>% inner_join(valid_p1, by = c("Pair", "UniqueID")) %>% rename(Batch_X = Batch, X_Val = logFC_Naive)
    df_p2 <- naive_fc_df %>% filter(Platform == p2) %>% inner_join(valid_p2, by = c("Pair", "UniqueID")) %>% rename(Batch_Y = Batch, Y_Val = logFC_Naive)
    inner_join(df_p1, df_p2, by = c("UniqueID", "Pair"), relationship = "many-to-many") %>%
        mutate(Comp = name)
}

plot_data_fc <- bind_rows(
    build_comp("DIA", "OLK", "DIA vs OLK"),
    build_comp("DIA", "SOM", "DIA vs SOM"),
    build_comp("SOM", "OLK", "SOM vs OLK")
) %>%
    left_join(triple_consensus, by = c("Pair", "UniqueID")) %>%
    mutate(
        Is_Triple = replace_na(Is_Triple, FALSE),
        Visibility = ifelse(Is_Triple, "Triple", "Pairwise"),
        Pair = factor(Pair, levels = c("N/P", "M/F"))
    ) %>%
    arrange(Visibility, Pair)

stats_text_list <- list()
for (comp_name in unique(plot_data_fc$Comp)) {
    for (pair_name in unique(plot_data_fc$Pair)) {
        df_sub <- plot_data_fc %>% filter(Comp == comp_name, Pair == pair_name)
        if(nrow(df_sub) == 0) next
        n_tot <- n_distinct(df_sub$UniqueID)
        r_tot <- sprintf("%.2f", cor(df_sub$X_Val, df_sub$Y_Val, method = "pearson", use = "pairwise.complete.obs"))
        rho_tot <- sprintf("%.2f", cor(df_sub$X_Val, df_sub$Y_Val, method = "spearman", use = "pairwise.complete.obs"))
        parse_tot <- paste0("'\u25CB Pairwise (' * italic(n) == ", n_tot, " * '):' ~ italic(r) == ", r_tot, " * ',' ~ italic(rho) == ", rho_tot)
        df_cons <- df_sub %>% filter(Visibility == "Triple")
        n_cons <- n_distinct(df_cons$UniqueID)
        r_cons <- if(nrow(df_cons) > 2) sprintf("%.2f", cor(df_cons$X_Val, df_cons$Y_Val, method = "pearson", use = "pairwise.complete.obs")) else "NA"
        rho_cons <- if(nrow(df_cons) > 2) sprintf("%.2f", cor(df_cons$X_Val, df_cons$Y_Val, method = "spearman", use = "pairwise.complete.obs")) else "NA"
        parse_cons <- paste0("'\u25CF Triple (' * italic(n) == ", n_cons, " * '):' ~ italic(r) == ", r_cons, " * ',' ~ italic(rho) == ", rho_cons)
        stats_text_list[[paste(comp_name, pair_name)]] <- data.frame(
            Comp = comp_name, Pair = pair_name, n_tot, r_tot, rho_tot, n_cons, r_cons, rho_cons, parse_label = c(parse_tot, parse_cons), order = c(1, 2)
        )
    }
}
stats_df <- bind_rows(stats_text_list)

limit_val <- max(abs(c(plot_data_fc$X_Val, plot_data_fc$Y_Val)), na.rm = TRUE) * 0.85
axis_limits <- c(-limit_val, limit_val)
gap <- limit_val * 0.15
base_y <- limit_val * 0.85
stats_df <- stats_df %>% mutate(x_pos = -limit_val * 0.95, y_pos = ifelse(order == 1, base_y, base_y - gap))

p_scatter <- ggplot(plot_data_fc, aes(x = X_Val, y = Y_Val)) +
    geom_vline(xintercept = 0, color = "grey80", linewidth = 0.3) +
    geom_hline(yintercept = 0, color = "grey80", linewidth = 0.3) +
    geom_abline(intercept = 0, slope = 1, linetype = "dotted", color = "grey80", linewidth = 0.5) +
    geom_point(data = filter(plot_data_fc, Visibility == "Pairwise" & Pair == "N/P"), color = "grey80", shape = 16, size = 0.6, alpha = 0.5) +
    geom_point(data = filter(plot_data_fc, Visibility == "Pairwise" & Pair == "M/F"), color = "grey80", shape = 16, size = 0.6, alpha = 0.5) +
    geom_point(data = filter(plot_data_fc, Visibility == "Triple" & Pair == "N/P"), aes(fill = Comp), color = "white", shape = 21, size = 1.2, stroke = 0.2) +
    geom_point(data = filter(plot_data_fc, Visibility == "Triple" & Pair == "M/F"), aes(fill = Comp), color = "white", shape = 21, size = 1.2, stroke = 0.2) +
    geom_text(data = stats_df, aes(x = x_pos, y = y_pos, label = parse_label), color = "black", hjust = 0, size = 2.2, parse = TRUE, inherit.aes = FALSE) +
    facet_grid(Pair ~ Comp) +
    scale_x_continuous(limits = axis_limits, expand = c(0,0)) +
    scale_y_continuous(limits = axis_limits, expand = c(0,0)) +
    scale_color_manual(values = combo_colors) +
    scale_fill_manual(values = combo_colors) +
    labs(x = expression(log[2]*"Ratio of platform X"), y = expression(log[2]*"Ratio of platform Y")) +
    plasmix_theme +
    theme(
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.35),
        axis.line.x = element_blank(), axis.line.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.spacing = unit(0.15, "lines"),
        legend.position = "none",
        strip.background = element_rect(fill = "grey95")
    )

# 7. Assemble and export ----
rowtop <- ggarrange(
    p_pvca_final + theme(axis.title.x = element_text(hjust = 0.5)),
    p_srr_ridge, fig_pca_combo, nrow = 1,
    labels = c("a", "b", "c"), widths = c(1.2, 1.1, 1.4),
    label.x = 0, label.y = 1, hjust = -0.2, vjust = 1.2, font.label = label_style
)
rowbottom <- ggarrange(
    p_icc_temple, p_scatter + theme(plot.margin = margin(5, 5, 3.8, 5)), nrow = 1, labels = c("d", "e"), widths = c(1, 1.25),
    label.x = 0, label.y = 1, hjust = -0.2, vjust = 1.2, font.label = label_style
)
figure5 <- ggarrange(rowtop, rowbottom, nrow = 2, heights = c(1, 1.45))
ggsave("figures/fig5_sample_reference_ratio.pdf", figure5, width = 10, height = 6.3)
ggsave("figures/fig5_sample_reference_ratio.png", figure5, width = 10, height = 6.3, dpi = 600, bg = "white")
message("Figure 5 completed: figures/fig5_sample_reference_ratio.pdf；source data: tables/SourceData_Figure5.xlsx")

output_list <- list(
    "PVCA" = pvca_plot_data,
    "PCA_scores" = pca_scores_source,
    "ICC_values" = icc_plot_df,
    "ICC_summary" = icc_summary,
    "Cross_platform_values" = plot_data_fc,
    "Cross_platform_summary" = stats_df %>% select(-parse_label, -order, -x_pos, -y_pos) %>% distinct()
)
write.xlsx(output_list, "tables/SourceData_Figure5.xlsx", overwrite = TRUE, keepNA = TRUE, na.string = "NA")
